version: "3.8"
services:
  frontend:
    build: 
      context: ./src/frontend/
    container_name: frontend_app
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/frontend
  backend:
    build: 
      context: ./src/backend/app
    container_name: backend_app
    networks:
      - default
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_PASSWORD=titan
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PORT=5432
    volumes: 
      - ./src/backend/app:/app
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: titan
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:

networks:
  default:
    driver: bridge